---
title: "Group assignment"
author: "Dave Anderson, Longhao Chen, Tingrui Huang, Yudi Mao"
date: "11/26/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(benford.analysis) # loads package data(corporate.payment) # loads data
#This step is to find datasets provided in the package.
d <- data(package = "benford.analysis")
## names of data sets in the package
#d$results[, "Item"]
data(census.2009)

#The first code is to look at the high level test of reasonableness.
census1 <- benford(census.2009$pop.2009, number.of.digits = 1, sign = "positive", discrete = TRUE, round = 3)
#We can take a closer look at the first two digits, which is designed to select audit targets.
census2 <- benford(census.2009$pop.2009, number.of.digits = 2, sign = "positive", discrete = TRUE, round = 3)

plot(census1)
#From this plot we can see that rea dotted line, which is the benford line, generally matches good with the bar plot. There are some disgrepencies for the second order test starting at 3 digits.

plot(census2)
#This plot reveals a closer look at first two digits data.

```
By looking at the general information of the dataset. We can see that the values of mean, variance, Ex.Kurtosis and skewness well match with the expected values of 0.5, 0.0833, -1.2, and 0.
```{r}
census1
```


```{r}
#This step is to find the suspicious targets using the first 2 digits Benford model.
suspects <- getSuspects(census2, census.2009)
suspects
```

From the suspect function, we can see that Alabama state has a handful of data that are suspicious.
